server:
  port: 8086
#FreeMarker
#pring:
#  freemarker:
#    allow-request-override: false
#    cache: false
#    check-template-location: true
#    charset: UTF-8
#    content-type: text/html
#    expose-request-attributes: false
#    expose-session-attributes: false
#    expose-spring-macro-helpers: false
#    suffix: .ftl
spring:
  datasource:
    name: upload
    url: jdbc:mysql://localhost:3306/upload?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


mybatis:
  mapper-locations:  classpath:mapper/*Mapper.xml
#  type-aliases-package: com.tang.upload.model


#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


##上传图片保存的路径
#img:
#  location: /Downloads/imgUpload/

#配置上传文件的最大值
servlet:
  multipart:
    max-file-size: 5Mb
    max-request-size: 50Mb

#自定义文件上传路径
web:
  upload-path: /Downloads/imgUpload/









